<a href="https://colab.research.google.com/github/Vaishnavi-appidi/vaishu/blob/main/icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
# Generate an array of 15 random integers between 1 and 20
vec= np.random.randint(1, 21, size=15)
# Reshape to a 3x5 matrix
arr= vec.reshape(3, 5)
#print array shape
print("Array shape:", arr.shape)
#replace max in each row by 0
arr[np.arange(len(arr)),arr.argmax(axis=1)] = 0
print(arr)

Array shape: (3, 5)
[[ 0  2  2  3  1]
 [ 4  2  0  1 17]
 [16 16  0 11 11]]


In [6]:
import numpy as np
# Create a 2D array (4x3) with specified integers
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
#Print the type,shape and datatype of the array
print("Array shape:", b.shape)
print("Array type:", type(b))
print("Array data type:", b.dtype)
print(b)

Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Array data type: int32
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np
# Creating a 2x2 matrix
c = np.array([[3, -2], [1, 0]])
# eigenvalues and right eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(c)
print("Eigenvalues", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)

Eigenvalues [2. 1.]
Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [10]:
import numpy as np
d= np.array([[0, 1, 2], [3, 4, 5]])
# sum of the diagonal elements of the matrix
sum= np.trace(d)
print("Sum of diagonal elements:", sum)

Sum of diagonal elements: 4


In [15]:
import numpy as np
e= np.array([[1, 2], [3, 4], [5, 6]])
# Reshape the matrix 3x2 and 2x3 matrix
f= e.reshape((2, 3))
g=e.reshape(3,2)
print("Original array:\n", e)
print("Reshaped array 2x3:\n", f)
print("Reshaped array 3x2:\n", g)


Original array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array 2x3:
 [[1 2 3]
 [4 5 6]]
Reshaped array 3x2:
 [[1 2]
 [3 4]
 [5 6]]
